Repository rubygems/bundler-site, pull requests merged in 2022-12, with the labels that each got.

#966 Make buttons easier to read
  assets/stylesheets/_bootstrap-class-overrides.scss
  assets/stylesheets/_bootstrap-variable-overrides.scss
  assets/stylesheets/application.css.scss
Labels: architecture/legacy or broken, accessibility

#985 Use Bundler 2.4.1
  Gemfile.lock
Labels: architecture/maintenance

#983 Update compatible versions of Ruby/RubyGems with Bundler 2.4
  source/compatibility.html.haml
Labels: content/validation

#991 Add Bundler 2.4 to documentation
  helpers/config_helper.rb
  source/v2.4/docs.html.haml
  source/v2.4/whats_new.html.haml
Labels: architecture/maintenance

#990 Revert "Redirect to the latest man page when version isn't specified"
  config.rb
Labels: regression, architecture/legacy or broken, accessibility

#993 Stop making plain text pages available at the top level
  config.rb
  lib/tasks/man_generator/man.rake
Labels: architecture/legacy or broken

#994 Redirect to the latest man page when version isn't specified
  config.rb
Labels: architecture/maintenance

#995 Update internal links to versioned guides with the latest ones
  source/blog/2018-06-07-may-bundler-update.html.markdown
  source/blog/2018-09-10-august-bundler-update.html.markdown
  source/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
Labels: content/cleanup

#997 Update activesupport from 7.0.3.1 to 7.0.4
  Gemfile.lock
Labels: architecture/maintenance

#998 Use https instead of http for links to slack.bundler.io
  source/localizable/index.html.haml
Labels: security, accessibility

#999 Update middleman-search to edge to use Ruby 3.2
  Gemfile
  Gemfile.lock
Labels: architecture/cleanup, architecture/maintenance

#984 Update Ruby from 3.1.3 to 3.2.0
  .ruby-version
  Gemfile.lock
Labels: ruby, architecture/maintenance, architecture/legacy or broken
