Repository rubygems/bundler-site, pull requests merged in 2023-01, with the labels that each got.

#1000 Use the numbered parameters in calculating VERSIONS
  lib/versions.rb
Labels: architecture/maintenance

#841 Replace missing forked ronn-ng with public nronn
  Gemfile
  Gemfile.lock
Labels: ruby, regression

#1005 Update middleman from 038f4f60 to 50f76c29
  Gemfile
  Gemfile.lock
Labels: architecture/legacy or broken

#1006 Rewrite guides/bundler_workflow from HAML to Markdown
  source/guides/bundler_workflow.html.haml
  source/guides/bundler_workflow.html.md
Labels: content/cleanup, design, contributor experience

#1007 Use the absolute link in guides/bundler_workflow
  source/guides/bundler_workflow.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility

#1008 HAML-Lint: cleanup UnnecessaryStringOutput
  .haml-lint.yml
  source/layouts/base.haml
Labels: architecture/legacy or broken, static analysis

#1009 Update nronn from 0.10.2 to 0.11.1
  Gemfile.lock
Labels: dependencies, ruby

#1010 Update kramdown-parser-gfm from 1.0.1 to 1.1.0
  Gemfile.lock
Labels: dependencies, ruby, architecture/maintenance

#1011 Update rack from 2.2.4 to 2.2.5
  Gemfile.lock
Labels: dependencies, ruby

#1012 Update oj from 3.13.21 to 3.13.22
  Gemfile.lock
Labels: dependencies, ruby, architecture/maintenance

#1013 Update racc from 1.6.1 to 1.6.2
  Gemfile.lock
Labels: ruby

#1014 Update public_suffix from 5.0.0 to 5.0.1
  Gemfile.lock
Labels: dependencies, ruby, architecture/maintenance

#1015 Update minitest from 5.16.3 to 5.17.0
  Gemfile.lock
Labels: dependencies, ruby, architecture/maintenance

#1016 Update caniuse-lite from 1.0.30001285 to 1.0.30001441
  package-lock.json
Labels: dependencies, javascript, architecture/maintenance, accessibility

#1017 Update padrino-helpers from 0.15.1 to 0.15.2
  Gemfile.lock
Labels: dependencies, ruby, architecture/maintenance

#1018 Introduce rubocop-rake as one of RuboCop linters
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby, architecture/maintenance, contributor experience, static analysis

#1019 Update browserslist from 4.18.1 to 4.21.4
  package-lock.json
Labels: dependencies, javascript, design, architecture/maintenance, accessibility

#1020 Update terser from 5.14.2 to 5.16.1
  package-lock.json
Labels: dependencies, javascript, architecture/maintenance

#1022 Unify bundler_setup guide into version-independent one
  config.rb
  source/v1.15/guides/bundler_setup.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1023 Unify sinatra guide into version-independent one
  config.rb
  source/v1.15/guides/sinatra.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1025 Rewrite guides/sinatra from HAML to Markdown
  source/guides/sinatra.html.haml
  source/guides/sinatra.html.md
Labels: content/cleanup, accessibility

#1026 Unify git_bisect guide into version-independent one
  config.rb
  source/v1.15/guides/git_bisect.html.md
Labels: content/cleanup, accessibility, contributor experience

#1027 Unify rails guide into version-independent one
  config.rb
  source/v1.15/guides/rails.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1028 Unify bundler_sharing guide into version-independent one
  config.rb
  source/v1.15/guides/bundler_sharing.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1029 Update rubocop from 1.41.1 to 1.42.0
  Gemfile.lock
Labels: dependencies, ruby

#1030 Unify groups guide into version-independent one
  config.rb
  source/v1.15/guides/groups.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1031 Update bin/rake by re-running bundle binstubs rake
  bin/rake
Labels: architecture/cleanup

#1032 Unify updating_gems guide into version-independent one
  config.rb
  source/v1.15/guides/updating_gems.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1033 Unify deploying guide into version-independent one
  config.rb
  source/v1.15/guides/deploying.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1034 Update postcss from 8.4.19 to 8.4.20
  package-lock.json
Labels: dependencies, javascript

#1035 Unify faq guide into version-independent one
  config.rb
  source/v1.15/guides/faq.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1036 Unify git guide into version-independent one
  config.rb
  source/guides/git.html.haml
  source/v1.15/guides/git.html.haml
Labels: content/cleanup, accessibility, contributor experience

#1037 Unify creating_gem guide into version-independent one
  config.rb
  source/localizable/v1.15/guides/creating_gem.en.html.md
  source/localizable/v1.15/guides/creating_gem.pl.html.md
Labels: content/cleanup, accessibility, contributor experience

#1038 Unify using_bundler_in_applications guide into version-independent one
  config.rb
  source/localizable/v1.15/guides/using_bundler_in_applications.en.html.md
  source/localizable/v1.15/guides/using_bundler_in_applications.pl.html.md
Labels: content/cleanup, accessibility, contributor experience

#1039 Unify v1.15 guides in es into version-independent ones
  config.rb
  source/localizable/v1.15/guides/bundler_setup.es.html.haml
  source/localizable/v1.15/guides/bundler_sharing.es.html.haml
Labels: content/cleanup, architecture/cleanup, accessibility, contributor experience

#1041 Update dead links to Fastly with the new one
  source/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
  source/v1.15/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
Labels: content/cleanup, content/validation

#1042 Unify tls_ssl_troubleshooting guide to the latest one
  config.rb
  source/v1.15/guides/rubygems_tls_ssl_troubleshooting_guide.html.md
Labels: content/cleanup, contributor experience, content/validation

#1043 Use https in links to github.com
  source/blog/2017-03-28-bundler-1-14-so-many-fixes.html.markdown
  source/blog/2018-01-17-making-gem-development-a-little-better.html.markdown
  source/blog/2018-09-10-august-bundler-update.html.markdown
  source/localizable/guides/creating_gem.en.html.md
  source/localizable/guides/creating_gem.pl.html.md
Labels: security, content/cleanup

#1045 Rewrite guides/bundler_plugins from HAML to Markdown
  source/guides/bundler_plugins.html.haml
  source/guides/bundler_plugins.html.md
Labels: content/cleanup, architecture/cleanup, contributor experience

#1046 Rewrite guides/rails from HAML to Markdown
  source/guides/rails.html.haml
  source/guides/rails.html.md
Labels: content/cleanup, accessibility, contributor experience, content/validation

#1047 Rewrite about from HAML to Markdown
  source/localizable/about.en.html.haml
  source/localizable/about.en.html.md
Labels: content/cleanup, accessibility, contributor experience, content/validation

#1048 Update rgl from 0.5.9 to 0.5.10
  Gemfile.lock
Labels: dependencies, ruby

#1049 Update bundler from 2.4.1 to 2.4.2
  Gemfile.lock
Labels: dependencies, ruby

#1050 Update terser from 1.1.12 to 1.1.13
  Gemfile.lock
Labels: dependencies, ruby, architecture/maintenance

#1053 Remove exceptions for IdNames linter from .haml-lint.yml
  .haml-lint.yml
Labels: static analysis

#1054 Rewrite FAQ from HAML to Markdown
  source/guides/faq.html.haml
  source/guides/faq.html.md
Labels: content/cleanup, architecture/maintenance, accessibility, content/validation

#1055 Rewrite rationale from HAML to Markdown
  source/guides/rationale.html.haml
  source/guides/rationale.html.md
Labels: content/cleanup, architecture/maintenance, accessibility, content/validation

#1056 Rewrite deploying from HAML to Markdown
  source/guides/deploying.html.haml
  source/guides/deploying.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility, contributor experience

#1057 Rewrite deploying guide from HAML to Markdown
  source/guides/gemfile.html.haml
  source/guides/gemfile.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility, contributor experience

#1051 Rewrite all existing what's new pages from HAML to Markdown
  source/v1.12/whats_new.html.haml
  source/v1.12/whats_new.html.md
  source/v1.13/whats_new.html.haml
  source/v1.13/whats_new.html.md
  source/v1.14/whats_new.html.haml
  source/v1.14/whats_new.html.md
  source/v1.15/whats_new.html.haml
  source/v1.15/whats_new.html.md
  source/v1.16/whats_new.html.haml
  source/v1.16/whats_new.html.md
  source/v1.17/whats_new.html.haml
  source/v1.17/whats_new.html.md
  source/v2.0/whats_new.html.haml
  source/v2.0/whats_new.html.md
  source/v2.1/whats_new.html.haml
  source/v2.1/whats_new.html.md
  source/v2.2/whats_new.html.haml
  source/v2.2/whats_new.html.md
  source/v2.3/whats_new.html.haml
  source/v2.3/whats_new.html.md
  source/v2.4/whats_new.html.haml
  source/v2.4/whats_new.html.md
Labels: content/cleanup, architecture/cleanup, architecture/maintenance, architecture/legacy or broken, accessibility, content/validation

#1058 Rewrite gemfile_ruby guide from HAML to Markdown
  source/guides/gemfile_ruby.html.haml
  source/guides/gemfile_ruby.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility, contributor experience

#1052 Replace whats_new template in HAML with Markdown
  lib/tasks/versions.rake
  lib/templates/whats_new.html.haml.erb
  lib/templates/whats_new.html.md.erb
Labels: architecture/cleanup, architecture/legacy or broken, accessibility

#1059 Rewrite rubymotion guide from HAML to Markdown
  source/guides/rubymotion.html.haml
  source/guides/rubymotion.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility, contributor experience

#1060 Rewrite rubygems guide from HAML to Markdown
  source/guides/rubygems.html.haml
  source/guides/rubygems.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility, contributor experience

#1061 Rewrite groups guide from HAML to Markdown
  source/guides/groups.html.haml
  source/guides/groups.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility, contributor experience

#1063 Rewrite updating_gems guide from HAML to Markdown
  source/guides/updating_gems.html.haml
  source/guides/updating_gems.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility

#1062 Rewrite git guide from HAML to Markdown
  source/guides/git.html.haml
  source/guides/git.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility, contributor experience

#1064 Rewrite getting_started guide from HAML to Markdown
  source/guides/getting_started.html.haml
  source/guides/getting_started.html.md
Labels: content/cleanup, architecture/legacy or broken, accessibility, contributor experience

#1065 Add current_version to whats_new link
  source/localizable/index.html.haml
Labels: architecture/legacy or broken

#1068 Rewrite bundler_setup guide (en, es) from HAML to Markdown
  source/guides/bundler_setup.html.haml
  source/guides/bundler_setup.html.md
  source/localizable/guides/bundler_setup.es.html.haml
  source/localizable/guides/bundler_setup.es.html.md
Labels: architecture/legacy or broken, accessibility, contributor experience

#1069 Rewrite bundler_sharing guide (en, es) from HAML to Markdown
  source/guides/bundler_sharing.html.haml
  source/guides/bundler_sharing.html.md
  source/localizable/guides/bundler_sharing.es.html.haml
  source/localizable/guides/bundler_sharing.es.html.md
Labels: architecture/legacy or broken, accessibility, contributor experience

#1070 Good bye, Pry: replace it with irb
  Gemfile
  Gemfile.lock
Labels: dependencies, ruby, contributor experience

#1071 You do not have to reuqire rubygems on Ruby 1.9+
  source/guides/bundler_setup.html.md
  source/guides/bundler_workflow.html.md
  source/guides/getting_started.html.md
  source/guides/groups.html.md
  source/guides/rationale.html.md
  source/guides/sinatra.html.md
  source/localizable/guides/bundler_setup.es.html.md
Labels: content/cleanup, content/validation
